org: domenicocammarota
app: web-service
service: web-service
frameworkVersion: '2'
useDotenv: true

provider:
    name: aws
    region: ${env:REGION}

custom:
    stage: ${env:STAGE}
    prefix: ${self:service}-${self:custom.stage}
    vpcId:
        Fn::ImportValue: network-${self:custom.stage}-vpc-id
    PublicSubnetAZ0ID:
        Fn::ImportValue: network-${self:custom.stage}-public-subnet-az0-id
    PublicSubnetAZ1ID:
        Fn::ImportValue: network-${self:custom.stage}-public-subnet-az1-id
    MainClusterName: clusters-${self:custom.stage}-main-cluster
    MainClusterArn:
        Fn::ImportValue: clusters-${self:custom.stage}-main-cluster-arn
    WebSecurityGroupId:
        Fn::ImportValue: network-${self:custom.stage}-web-security-group-id

resources:
    Resources:

        # This service manages instances of the web task
        WebService:
            Type: AWS::ECS::Service
            DependsOn:
                - WebListener
            Properties:
                Cluster: ${self:custom.MainClusterArn}
                DeploymentConfiguration:
                    DeploymentCircuitBreaker:
                        Enable: true
                        Rollback: false
                DesiredCount: 1
                HealthCheckGracePeriodSeconds: 20
                LaunchType: EC2
                LoadBalancers:
                    - TargetGroupArn: !Ref WebTargetGroup
                      ContainerName: web-container
                      ContainerPort: 3000
                PlacementStrategies:
                    - Type: binpack
                      Field: MEMORY
                SchedulingStrategy: REPLICA
                ServiceName: web-service
                TaskDefinition: !Ref WebTaskDefinition

        WebTaskDefinition:
            Type: AWS::ECS::TaskDefinition
            Properties:
                ContainerDefinitions:
                    - Essential: true
                      Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/web:latest"
                      LogConfiguration:
                          LogDriver: awslogs
                          Options:
                              awslogs-region: ${self:provider.region}
                              awslogs-group: !Ref WebTaskLogGroup
                      Name: web-container
                      PortMappings:
                          - ContainerPort: 3000
                            HostPort: 0
                            Protocol: tcp
                Cpu: 512
                Family: web-task
                Memory: 756
                RequiresCompatibilities:
                    - EC2

        WebTaskLogGroup:
            Type: AWS::Logs::LogGroup
            Properties:
                LogGroupName: ${self:custom.prefix}-log-group

        WebLoadBalancer:
            Type: AWS::ElasticLoadBalancingV2::LoadBalancer
            Properties:
                IpAddressType: ipv4
                LoadBalancerAttributes:
                    - Key: access_logs.s3.enabled
                      Value: false
                    - Key: deletion_protection.enabled
                      Value: false
                Name: ${self:custom.prefix}-alb
                Scheme: internet-facing
                Subnets:
                    - ${self:custom.PublicSubnetAZ0ID}
                    - ${self:custom.PublicSubnetAZ1ID}
                SecurityGroups:
                    - ${self:custom.WebSecurityGroupId}
                Type: application

        WebTargetGroup:
            Type: AWS::ElasticLoadBalancingV2::TargetGroup
            Properties:
                HealthCheckIntervalSeconds: 6
                HealthCheckPath: /health
                HealthCheckPort: traffic-port
                HealthCheckProtocol: HTTP
                HealthCheckTimeoutSeconds: 5
                HealthyThresholdCount: 2
                HealthCheckEnabled: true
                Matcher:
                    HttpCode: 200
                Name: ${self:custom.prefix}-tg
                Port: 3000
                Protocol: HTTP
                TargetGroupAttributes:
                    - Key: stickiness.enabled
                      Value: false
                    - Key: deregistration_delay.timeout_seconds
                      Value: 300
                    - Key: stickiness.app_cookie.cookie_name
                      Value: ""
                    - Key: stickiness.type
                      Value: lb_cookie
                    - Key: stickiness.lb_cookie.duration_seconds
                      Value: 86400
                    - Key: slow_start.duration_seconds
                      Value: 0
                    - Key: stickiness.app_cookie.duration_seconds
                      Value: 86400
                    - Key: load_balancing.algorithm.type
                      Value: round_robin
                TargetType: instance
                UnhealthyThresholdCount: 2
                VpcId: ${self:custom.vpcId}

        WebListener:
            Type: AWS::ElasticLoadBalancingV2::Listener
            Properties:
                LoadBalancerArn: !Ref WebLoadBalancer
                Port: 80
                Protocol: HTTP
                DefaultActions:
                    - Order: 1
                      TargetGroupArn: !Ref WebTargetGroup
                      Type: forward

        WebScalingTarget:
            Type: AWS::ApplicationAutoScaling::ScalableTarget
            Properties:
                MaxCapacity: 5
                MinCapacity: 1
                ResourceId: !Sub "service/${self:custom.MainClusterName}/${WebService.Name}"
                RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService"
                ScalableDimension: ecs:service:DesiredCount
                ServiceNamespace: ecs
                SuspendedState:
                    DynamicScalingInSuspended: false
                    DynamicScalingOutSuspended: false
                    ScheduledScalingSuspended: false

        WebScalingPolicy:
            Type: AWS::ApplicationAutoScaling::ScalingPolicy
            Properties:
                PolicyName: ${self:custom.prefix}-web-sp
                PolicyType: TargetTrackingScaling
                ScalableDimension: ecs:service:DesiredCount
                ScalingTargetId: !Ref WebScalingTarget
                ServiceNamespace: ecs
                TargetTrackingScalingPolicyConfiguration:
                    PredefinedMetricSpecification:
                        PredefinedMetricType: ECSServiceAverageCPUUtilization
                    ScaleInCooldown: 30
                    ScaleOutCooldown: 30
                    TargetValue: 75


# # ---------- Policies/Roles ----------
#
#
#         # This is the role assummed by the Web Service
#         WebServiceRole:
#             Type: AWS::IAM::Role
#             Properties:
#                 AssumeRolePolicyDocument:
#                     {
#                         "Version": "2008-10-17",
#                         "Statement": [
#                             {
#                                 "Action": "sts:AssumeRole",
#                                 "Effect": "Allow",
#                                 "Principal": {
#                                     "Service": "ecs.amazonaws.com"
#                                 }
#                             }
#                         ]
#                     }
#                 ManagedPolicyArns:
#                     - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole
#                 RoleName: ${self:custom.prefix}-ecs-service-role
